-- BaoyanPilot forum content moderation.
-- Run this file in the Supabase SQL Editor after the forum_posts and forum_replies tables exist.
-- The browser performs the same check for immediate feedback; these triggers are the authoritative fallback.

create table if not exists public.forum_blocked_terms (
  id bigint generated by default as identity primary key,
  term text not null unique,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  constraint forum_blocked_terms_not_blank check (length(trim(term)) > 0)
);

alter table public.forum_blocked_terms enable row level security;
revoke all on public.forum_blocked_terms from anon, authenticated;

insert into public.forum_blocked_terms (term)
values
  ('傻逼'), ('傻b'), ('傻比'), ('傻币'), ('煞笔'),
  ('草泥马'), ('操你妈'), ('艹你妈'), ('草你妈'), ('你妈逼'), ('尼玛逼'),
  ('他妈的'), ('妈的'), ('狗娘养的'), ('狗东西'), ('王八蛋'), ('杂种'),
  ('贱人'), ('婊子'), ('脑残'), ('智障'), ('滚你妈'), ('滚蛋'), ('去死'),
  ('死全家'), ('全家死'), ('杀了你'), ('弄死你'), ('打死你'), ('烧死你'),
  ('砍死你'), ('燃烧吧家人'), ('fuckyou'), ('motherfucker'), ('asshole'),
  ('shithead'), ('bitch')
on conflict (term) do update set enabled = true;

create or replace function public.normalize_forum_moderation_text(input_text text)
returns text
language sql
immutable
set search_path = public
as $$
  select regexp_replace(
    replace(
      replace(
        translate(
          lower(coalesce(input_text, '')),
          'ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ０１２３４５６７８９',
          'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz0123456789'
        ),
        chr(8203),
        ''
      ),
      chr(65279),
      ''
    ),
    '[[:space:][:punct:]，。！？、；：…—（）【】《》“”‘’·]+',
    '',
    'g'
  );
$$;

create or replace function public.forum_content_is_blocked(input_text text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.forum_blocked_terms blocked
    where blocked.enabled
      and public.normalize_forum_moderation_text(blocked.term) <> ''
      and position(
        public.normalize_forum_moderation_text(blocked.term)
        in public.normalize_forum_moderation_text(input_text)
      ) > 0
  );
$$;

create or replace function public.moderate_forum_post_content()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.forum_content_is_blocked(coalesce(new.title, '') || ' ' || coalesce(new.content, '')) then
    raise exception using
      errcode = 'P0001',
      message = '内容包含辱骂、威胁或其他不友善用语，请修改后再发布。';
  end if;
  return new;
end;
$$;

create or replace function public.moderate_forum_reply_content()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.forum_content_is_blocked(new.content) then
    raise exception using
      errcode = 'P0001',
      message = '内容包含辱骂、威胁或其他不友善用语，请修改后再发布。';
  end if;
  return new;
end;
$$;

drop trigger if exists moderate_forum_posts_before_write on public.forum_posts;
create trigger moderate_forum_posts_before_write
before insert or update of title, content on public.forum_posts
for each row execute function public.moderate_forum_post_content();

drop trigger if exists moderate_forum_replies_before_write on public.forum_replies;
create trigger moderate_forum_replies_before_write
before insert or update of content on public.forum_replies
for each row execute function public.moderate_forum_reply_content();

notify pgrst, 'reload schema';
